//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 03/04/2022 21:00:08
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Linq.Expressions;

namespace DevelSystem.Interfaces
{
    public partial interface IRepository<T>
    {
        Task<IQueryable<T>> All();
        IQueryable<T> GetBy(Expression<Func<T, bool>> expression);
        Task Add(T entity);
        void Update(T entity);
        Task AddAll(IList<T> entity);
        void Remove(T entity);
    }
}
