//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 04/04/2022 3:46:33
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace DevelSystem.Models
{
    public partial class Encuesta {

        public Encuesta()
        {
            this.Preguntas = new List<Pregunta>();
            OnCreated();
        }

        public virtual Guid Id { get; set; }

        [System.ComponentModel.DisplayName("Nombre de la encuesta")]
        public virtual string Nombre { get; set; }

        [System.ComponentModel.DisplayName("Descripción")]
        public virtual string Descripcion { get; set; }

        public virtual string Url { get; set; }

        [JsonIgnore]
        public virtual IList<Pregunta> Preguntas { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
