//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 04/04/2022 3:46:33
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace DevelSystem
{
    public partial class Respuesta {

        public Respuesta()
        {
            OnCreated();
        }

        public virtual Guid Id { get; set; }

        public virtual string ValorRespuesta { get; set; }

        public virtual string Titulo { get; set; }

        public virtual Guid EncuestaId { get; set; }

        public virtual Guid PreguntaId { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
